version: '3.3'

services:
  # Postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    build: .
    command: ["./bin/docker_start.sh"]
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
